name: dns_updater
description: A simple utility to update Google Domains DNS to the current public IP.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  http: ^0.13.1
  logging: ^1.0.1
